import { sanitizePptMarkup } from '../../../src/ppt/pptUtils';
import constants from '../../../src/constants';
import {hasTagsRegExp} from "../../../src/tags/tagUtils";

const XML = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr><p:sp><p:nvSpPr><p:cNvPr id="3" name="Espace réservé du contenu 2"><a:extLst><a:ext uri="{FF2B5EF4-FFF2-40B4-BE49-F238E27FC236}"><a16:creationId xmlns:a16="http://schemas.microsoft.com/office/drawing/2014/main" id="{E9FF9500-4E37-D3F0-DF7B-22F85CE05592}"/></a:ext></a:extLst></p:cNvPr><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr><p:ph idx="1"/></p:nvPr></p:nvSpPr><p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:pPr marL="0" indent="0"><a:buNone/></a:pPr><a:r><a:rPr lang="fr-FR" dirty="0"/><a:t>{{#</a:t></a:r><a:r><a:rPr lang="fr-FR" dirty="0" err="1"/><a:t>each</a:t></a:r><a:r><a:rPr lang="fr-FR" dirty="0"/><a:t> </a:t></a:r><a:r><a:rPr lang="fr-FR" dirty="0" err="1"/><a:t>persons</a:t></a:r><a:r><a:rPr lang="fr-FR" dirty="0"/><a:t>}}</a:t></a:r></a:p><a:p><a:r><a:rPr lang="fr-FR" dirty="0"/><a:t>{{</a:t></a:r><a:r><a:rPr lang="fr-FR" dirty="0" err="1"/><a:t>name</a:t></a:r><a:r><a:rPr lang="fr-FR"/><a:t>}}</a:t></a:r><a:endParaRPr lang="fr-FR" dirty="0"/></a:p><a:p><a:pPr marL="0" indent="0"><a:buNone/></a:pPr><a:r><a:rPr lang="fr-FR" dirty="0"/><a:t>{{#</a:t></a:r><a:r><a:rPr lang="fr-FR" dirty="0" err="1"/><a:t>endeach</a:t></a:r><a:r><a:rPr lang="fr-FR" dirty="0"/><a:t>}}</a:t></a:r></a:p></p:txBody></p:sp></p:spTree><p:extLst><p:ext uri="{BB962C8B-B14F-4D97-AF65-F5344CB8AC3E}"><p14:creationId xmlns:p14="http://schemas.microsoft.com/office/powerpoint/2010/main" val="4123187392"/></p:ext></p:extLst></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>'

test('sanitizePptMarkup', () => {
    const count = (XML.match(hasTagsRegExp(constants.delimiters)) || []).length;
    const xml = sanitizePptMarkup(XML, constants.delimiters);
    expect((XML.match(hasTagsRegExp()) || []).length).toEqual(count);
    expect((XML.match(/{{<[^{}]+}}/g) || []).length).toBeGreaterThan(0);
    expect((xml.match(/{{<[^{}]+}}/g) || []).length).toEqual(0);
});